[package]
name = "pest-ast-derive"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.38"
quote = "0.6.12"
proc-macro2 = "0.4.30"
pest_ast_generator = { path = ".." }
